
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # pegar a versao mais atualizada do codigo
      
      # instalar node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
   
      # instalar/atualizas as dependencias          
      - name: Install dependencies
        run: npm install
      
      # executar a build
      - name: Run build
        run: npm run-script build
        
      # copiar código para dentro da digital ocean
      - name: copy dist to digital ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/CatalogBotApi"
        
      # executar npm install na digital ocean e reiniciar o servidor
      - name: Install dependencies on digital ocean and restart server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd ~/app/CatalogBotApi
              npm install
              pm2 restart catalogbot-api
            

              
