
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # pegar a versao mais atualizada do codigo
      
      # instalar node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      # instalar as dependencias          
      - name: Install dependencies
        run: npm install
      
      # executar a build
      - name: Run build
        run: npm run-script build
        
      # copiar pasta dist para dentro da digital ocean
      - name: copy dist to digital ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
      # substituir o codigo existente na pasta dist pelo novo codigo
      # executar npm install na digital ocean
      # restart no servidor node.js
